# Add Cloud KMS CryptoKey Decrypter to cloudbuilder account

# https://cloud.google.com/kms/docs/iam
# https://cloud.google.com/kms/docs/reference/permissions-and-roles

do:
- gcloud kms keys add-iam-policy-binding CRYPTOKEY --location LOCATION --keyring KEYRING --member serviceAccount:00000000@cloudbuild.gserviceaccount.com --role roles/cloudkms.cryptoKeyDecrypter

undo:
- gcloud kms keys remove-iam-policy-binding CRYPTOKEY --location LOCATION --keyring KEYRING --member serviceAccount:00000000@cloudbuild.gserviceaccount.com --role roles/cloudkms.cryptoKeyDecrypter